version: '3.1'
services:
  client:
    image: elasticsearch-py
    build:
      context: .
      dockerfile: Dockerfile-py
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-py:/code/elasticsearch-py
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  dsl-client:
    image: elasticsearch-dsl-py
    build:
      context: .
      dockerfile: Dockerfile-dsl-py
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-dsl-py:/code/elasticsearch-dsl-py
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  elasticsearch:
      image: fxdgear/elasticsearch:${ELASTIC_VERSION:-5.5.0}
    ports:
      - "9200:9200"
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - script.inline=true
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test

networks:
  esnet:

volumes:
  esvol:
