version: '3.3'
services:
  client2:
    image: elasticsearch-py:2
    build:
      context: .
      dockerfile: Dockerfile-py.2
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-py:/code/elasticsearch-py
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  client3:
    image: elasticsearch-py:3
    build:
      context: .
      dockerfile: Dockerfile-py.3
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-py:/code/elasticsearch-py
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  dsl-client:
    image: elasticsearch-dsl-py
    build:
      context: .
      dockerfile: Dockerfile-dsl-py
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-dsl-py:/code/elasticsearch-dsl-py
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  elasticsearch:
    image: fxdgear/elasticsearch:${ELASTIC_VERSION:-5.5.0}
    ports:
      - "9200:9200"
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
networks:
  esnet:

volumes:
  esvol:
