FROM python:latest
RUN apt-get update && apt-get install git curl
COPY elasticsearch-py /code/elasticsearch-py
COPY elasticsearch /code/elasticsearch
WORKDIR /code/elasticsearch-py
RUN pip install ipdb
RUN pip install .[develop]
RUN python setup.py develop
COPY wait-for-elasticsearch.sh /code/wait-for-elasticsearch.sh
CMD ["/code/wait-for-elasticsearch.sh", "http://elasticsearch:9200", "--", "python", "setup.py", "test"]
