version: '3.3'
services:
  client:
    image: fxdgear/elasticsearch-py:${PYTHON_VERSION:-3}
    build:
      context: .
      dockerfile: Dockerfile
      args:
          PYTHON_VERSION: ${PYTHON_VERSION:-3}
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-py:/code/elasticsearch-py
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION:-6.2.4}
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "http.max_content_length=5mb"
  elasticsearch-basic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.3.0}
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
  squid:
    container_name: squid
    image: sameersbn/squid:3.5.27
    ports:
      - "3128:3128"
    volumes:
      - squid:/var/spool/squid
      - ./squid:/etc/squid
    networks:
      - esnet

networks:
  esnet:
volumes:
  esvol:
  squid:
