version: '3.3'
services:
  client2:
    image: elasticsearch-py:2
    build:
      context: .
      dockerfile: Dockerfile-py.2
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-py:/code/elasticsearch-py
      - esvol:/tmp
      - ./x-pack:/certs
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  client3:
    image: elasticsearch-py:3
    build:
      context: .
      dockerfile: Dockerfile-py.3
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-py:/code/elasticsearch-py
      - esvol:/tmp
      - ./x-pack:/certs
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  dsl-client:
    image: elasticsearch-dsl-py
    build:
      context: .
      dockerfile: Dockerfile-dsl-py
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-dsl-py:/code/elasticsearch-dsl-py
      - esvol:/tmp
      - ./x-pack:/certs
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  elasticsearch:
    image: fxdgear/elasticsearch:${ELASTIC_VERSION:-6.0.0-beta1}
    ports:
      - "9200:9200"
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false

  elasticsearch-xpack:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - "9201:9200"
    volumes:
      - esvol:/tmp
      - ./x-pack:/usr/share/elasticsearch/config/x-pack
    # user: root
    networks:
      esnet:
        ipv4_address: 172.16.238.10
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
      - "xpack.ssl.key=/usr/share/elasticsearch/config/x-pack/elasticsearch-xpack/elasticsearch-xpack.key"
      - "xpack.ssl.certificate=/usr/share/elasticsearch/config/x-pack/elasticsearch-xpack/elasticsearch-xpack.crt"
      - "xpack.ssl.certificate_authorities=/usr/share/elasticsearch/config/x-pack/ca/ca.crt"
      - "xpack.security.http.ssl.enabled=true"

networks:
  esnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24

volumes:
  esvol:
