version: '3.3'
services:
  client:
    image: fxdgear/elasticsearch-py:${PYTHON_VERSION:-3}
    build:
      context: .
      dockerfile: Dockerfile
      args:
          PYTHON_VERSION: ${PYTHON_VERSION:-3}
    dns:
      - 8.8.8.8
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - ./elasticsearch-py:/code/elasticsearch-py
      - esvol:/tmp
      - ./x-pack:/certs
    networks:
      - esnet
    depends_on:
      - elasticsearch
    command: ["true"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTIC_VERSION:-6.2.4}
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
      - "discovery.zen.ping.unicast.hosts=elasticsearch"

  elasticsearch-basic:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-6.2.4}
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false

  elasticsearch-platinum:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:${ELASTIC_VERSION:-6.2.4}
    ports:
      - "9201:9200"
    volumes:
      - esvol:/tmp
      - ./x-pack:/usr/share/elasticsearch/config/x-pack
    # user: root
    networks:
      esnet:
        ipv4_address: 172.16.238.10
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
      - "xpack.ssl.key=/usr/share/elasticsearch/config/x-pack/elasticsearch-xpack/elasticsearch-xpack.key"
      - "xpack.ssl.certificate=/usr/share/elasticsearch/config/x-pack/elasticsearch-xpack/elasticsearch-xpack.crt"
      - "xpack.ssl.certificate_authorities=/usr/share/elasticsearch/config/x-pack/ca/ca.crt"
      - "xpack.security.http.ssl.enabled=true"

networks:
  esnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24

volumes:
  esvol:
