FROM python:latest
RUN apt-get update && apt-get install git curl
ADD elasticsearch-dsl-py /code/elasticsearch-dsl-py
WORKDIR /code/elasticsearch-dsl-py
RUN pip install -e '.[develop]'
COPY wait-for-elasticsearch.sh /code/wait-for-elasticsearch.sh
CMD ["/code/wait-for-elasticsearch.sh", "http://elasticsearch:9200", "--", "python", "setup.py", "test"]
