version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    ports:
      - "9200:9200"
    networks:
      - esnet
    environment:
      - bootstrap.memory_lock=false

  client:
    image: appropriate/curl:latest
    networks:
      - esnet
    command: "curl http://elasticsearch:9200"
networks:
  esnet:

