version: "3.3"
services:
  # coordinating node. Used for Load balancing across containers
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=master"
      - "network.publish_host=elasticsearch"
      - "bootstrap.memory_lock=false"
      - "node.master=false"
      - "node.data=false"
      - "node.ingest=false"
      - "node.max_local_storage_nodes=3"
      - "xpack.ssl.key=/usr/share/elasticsearch/config/x-pack/elasticsearch/elasticsearch.key"
      - "xpack.ssl.certificate=/usr/share/elasticsearch/config/x-pack/elasticsearch/elasticsearch.crt"
      - "xpack.ssl.certificate_authorities=/usr/share/elasticsearch/config/x-pack/ca/ca.crt"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "foobar=$(HOSTNAME)"
    networks:
       - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    deploy:
      endpoint_mode: dnsrr
      mode: 'global'
      resources:
        limits:
          memory: 1G
    secrets:
      - source: elasticsearch.crt
        target: /usr/share/elasticsearch/config/x-pack/elasticsearch/elasticsearch.crt
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: elasticsearch.key
        target: /usr/share/elasticsearch/config/x-pack/elasticsearch/elasticsearch.key
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca.crt
        target: /usr/share/elasticsearch/config/x-pack/ca/ca.crt
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca.key
        target: /usr/share/elasticsearch/config/x-pack/ca/ca.key
        uid: '1000'
        gid: '1000'
        mode: 0440

  master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=master"
      - "bootstrap.memory_lock=false"
      - "network.publish_host=master"
      - "node.master=true"
      - "node.data=true"
      - "node.ingest=true"
      - "node.max_local_storage_nodes=3"
      - "xpack.ssl.key=/usr/share/elasticsearch/config/x-pack/master/master.key"
      - "xpack.ssl.certificate=/usr/share/elasticsearch/config/x-pack/master/master.crt"
      - "xpack.ssl.certificate_authorities=/usr/share/elasticsearch/config/x-pack/ca/ca.crt"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
    networks:
       - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      endpoint_mode: dnsrr
      mode: 'replicated'
      replicas: 2
      resources:
        limits:
          memory: 1G
    secrets:
      - source: master.crt
        target: /usr/share/elasticsearch/config/x-pack/master/master.crt
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: master.key
        target: /usr/share/elasticsearch/config/x-pack/master/master.key
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca.crt
        target: /usr/share/elasticsearch/config/x-pack/ca/ca.crt
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: ca.key
        target: /usr/share/elasticsearch/config/x-pack/ca/ca.key
        uid: '1000'
        gid: '1000'
        mode: 0440

  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.2
    environment:
      - "ELASTICSEARCH_URL=https://elasticsearch:9200"
    networks:
      - esnet
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host
    volumes:
      - ./kibana:/etc/kibana
    deploy:
      resources:
         limits:
           memory: 1G

secrets:
  master.key:
    external: true
  master.crt:
    external: true
  elasticsearch.crt:
    external: true
  elasticsearch.key:
    external: true
  ca.key:
    external: true
  ca.crt:
    external: true



volumes:
  esdata:
    driver: local
networks:
  esnet:
    driver: overlay
