version: '3.1'
services:
  kibana:
    image: 'fxdgear/kibana:4.6'
    build:
      context: ../
      dockerfile: kibana-4.6/Dockerfile
    networks:
      - esnet
    ports:
        - '5601:5601'
    deploy:
      mode: 'replicated'
      replicas: 1
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local
networks:
  esnet:
