version: '3.1'
services:
  elasticsearch:
    image: 'fxdgear/elasticsearch:2.4'
    build:
      context: ../
      dockerfile: elasticsearch-2.4/Dockerfile
    environment:
      - "ENV_TAG=--E"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HOST=http://localhost:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
        - '9200:9200'
    deploy:
      mode: 'replicated'
      replicas: 1
      resources:
        limits:
          memory: 1g
        ulimits:
          memlock:
            soft: -1
            hard: -1

volumes:
  esdata:
    driver: local
networks:
  esnet:
