discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.unicast.hosts: master
bootstrap.memory_lock: false
node.master: true
node.data: true
node.ingest: false
node.max_local_storage_nodes: 3
xpack.ssl.key: /usr/share/elasticsearch/config/x-pack/docker-cluster/docker-cluster.key
xpack.ssl.certificate: /usr/share/elasticsearch/config/x-pack/docker-cluster/docker-cluster.crt
xpack.ssl.certificate_authorities: /usr/share/elasticsearch/config/x-pack/ca/ca.crt
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true
network.bind_host: 0.0.0.0
network.publish_host: ${HOSTNAME}
