version: '3.1'
services:
  elasticsearch:
    image: 'fxdgear/elasticsearch:${ELASTIC_VERSION:-5.5.0}'
    build:
      context: ../
      args:
          ELASTIC_VERSION: ${ELASTIC_VERSION:-5.5.0}
      dockerfile: elasticsearch/Dockerfile
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HOST=http://elasticsearch:9200"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
        - '9200:9200'
    deploy:
      mode: 'replicated'
      replicas: 1
      resources:
        limits:
          memory: 1g
        ulimits:
          memlock:
            soft: -1
            hard: -1

volumes:
  esdata:
    driver: local
networks:
  esnet:
