ARG ELASTIC_VERSION=6.0.0-rc1

FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
USER root
COPY x-pack/ca /usr/share/elasticsearch/config/x-pack/ca
COPY x-pack/elasticsearch /usr/share/elasticsearch/config/x-pack/elasticsearch
COPY x-pack/master /usr/share/elasticsearch/config/x-pack/master
RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/config/x-pack
USER elasticsearch
