FROM python:3.4-alpine
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh curl
ADD elasticsearch-py /code/elasticsearch-py
WORKDIR /code/elasticsearch-py
RUN pip install requests==1.0.0 nose coverage mock pyaml nosexcover ipdb
RUN python setup.py develop
COPY wait-for-elasticsearch.sh wait-for-elasticsearch.sh
CMD ["./wait-for-elasticsearch.sh", "http://elasticsearch:9200", "--", "python", "setup.py", "test"]
